// Date: 14/08/2013 04:33:22
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class Modeltest extends ModelBase
{
  //fields
    ModelRenderer core;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
  
  public Modeltest()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      core = new ModelRenderer(this, 0, 0);
      core.addBox(0F, 0F, 0F, 4, 3, 4);
      core.setRotationPoint(0F, 0F, 0F);
      core.setTextureSize(64, 32);
      core.mirror = true;
      setRotation(core, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 24, 10);
      Shape1.addBox(0F, 0F, 0F, 8, 1, 2);
      Shape1.setRotationPoint(-2F, 1F, 1F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 28, 0);
      Shape2.addBox(0F, 0F, 0F, 2, 1, 6);
      Shape2.setRotationPoint(1F, 1F, -1F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    core.render(f5);
    Shape1.render(f5);
    Shape2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
